ollama:
  host: http://localhost:11434
  # model: llama3.2  # Optional: specify a model, or auto-detect will be used

# MCP Servers Configuration
servers:
  # Supabase PostgreSQL Server
  - name: supabase
    type: stdio
    autoConnect: true # Set to true to connect automatically when starting the client
    stdio:
      command: npx
      args:
        - '-y'
        - '@modelcontextprotocol/server-postgres'
        - 'postgresql://postgres:postgres@127.0.0.1:54322/postgres'

  # Linear API Server (SSE)
  - name: linear
    type: sse
    autoConnect: false # Set to true to connect automatically
    sse:
      url: 'https://mcp.linear.app/sse'
      reconnectDelay: 5000 # Reconnect after 5 seconds if connection drops

logging:
  level: info
session:
  persist: true
  storagePath: /Users/mayanksingh/.ollama-mcp/sessions
output:
  format: pretty
  colors: true
